development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: <%= ENV['MONGODB_URI'] %>
      # Otherwise define the parameters separately.
      # This defines the name of the default database that Mongoid can connect to.
      # (required).
      

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>